// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `default_config`, `to_archive_entry`

/// Build info for the embedded zipr_lib Rust crate.
Future<RustBuildInfo> rustBuildInfo() =>
    RustLib.instance.api.crateApiZiprApiRustBuildInfo();

/// List only the top-level entries of an archive. Nested archives are
/// flagged via `is_archive` and their children must be requested separately
/// via `list_archive_segment`. This avoids opening every nested archive on
/// initial load.
Future<List<ArchiveEntry>> listArchive({required String path}) =>
    RustLib.instance.api.crateApiZiprApiListArchive(path: path);

/// List the top-level entries inside a nested archive identified by its
/// zip expression (e.g. `outer.war!/BOOT-INF/lib/spring.jar`).
Future<List<ArchiveEntry>> listArchiveSegment({required String zipExpr}) =>
    RustLib.instance.api.crateApiZiprApiListArchiveSegment(zipExpr: zipExpr);

/// Walk the entire archive (including all nested archives) and return only
/// the full zip expressions of every leaf entry. Used by the Flutter side as
/// a one-time cache so subsequent draft extends can match new input files
/// without crossing the FFI boundary again.
Future<List<String>> enumerateArchivePaths({required String path}) =>
    RustLib.instance.api.crateApiZiprApiEnumerateArchivePaths(path: path);

/// Extract a single entry from an archive (supports nested paths with `!/`).
/// If `output_path` is provided, writes to that file; otherwise returns bytes.
Future<Uint8List> extractEntry({
  required String zipExpr,
  required String outputPath,
}) => RustLib.instance.api.crateApiZiprApiExtractEntry(
  zipExpr: zipExpr,
  outputPath: outputPath,
);

/// Delete an entry from an archive.
Future<void> deleteEntry({required String zipExpr}) =>
    RustLib.instance.api.crateApiZiprApiDeleteEntry(zipExpr: zipExpr);

/// Replace an entry in an archive with the contents of a source file.
Future<void> replaceEntry({
  required String zipExpr,
  required String sourcePath,
}) => RustLib.instance.api.crateApiZiprApiReplaceEntry(
  zipExpr: zipExpr,
  sourcePath: sourcePath,
);

/// Diff two archives recursively and return the list of differences.
Future<List<DiffEntry>> diffArchives({
  required String left,
  required String right,
}) =>
    RustLib.instance.api.crateApiZiprApiDiffArchives(left: left, right: right);

/// Generate a patch draft TOML spec from a source directory.
/// Returns the summary and the TOML content.
Future<DraftSummary> patchDraft({
  required String archive,
  required String fromDir,
  required String output,
}) => RustLib.instance.api.crateApiZiprApiPatchDraft(
  archive: archive,
  fromDir: fromDir,
  output: output,
);

/// Extend an existing patch draft spec with additional source files/directories.
/// Existing entries and unresolved items in the spec are preserved.
Future<DraftSummary> patchDraftExtend({
  required String archive,
  required String specPath,
  required List<String> additionalSources,
}) => RustLib.instance.api.crateApiZiprApiPatchDraftExtend(
  archive: archive,
  specPath: specPath,
  additionalSources: additionalSources,
);

/// Apply a patch spec to an archive.
/// Set `dry_run` to true to preview without modifying.
Future<ApplySummary> patchApply({
  required String archive,
  required String spec,
  required bool dryRun,
}) => RustLib.instance.api.crateApiZiprApiPatchApply(
  archive: archive,
  spec: spec,
  dryRun: dryRun,
);

/// Restore an archive from a previously-created backup file produced by `patch_apply`.
/// The backup is moved over the archive and removed on success.
Future<void> restoreArchiveBackup({
  required String archive,
  required String backup,
}) => RustLib.instance.api.crateApiZiprApiRestoreArchiveBackup(
  archive: archive,
  backup: backup,
);

/// Read a patch spec file leniently (no validation) and return its summary.
/// Used for reloading after external edits.
Future<DraftSummary> readPatchSpec({required String specPath}) =>
    RustLib.instance.api.crateApiZiprApiReadPatchSpec(specPath: specPath);

/// Apply resolutions to unresolved entries in a patch spec.
/// Each resolution either picks a target ("pick") or ignores the entry ("ignore").
/// Returns the updated summary after writing the modified spec back to disk.
Future<DraftSummary> patchResolve({
  required String specPath,
  required List<Resolution> resolutions,
}) => RustLib.instance.api.crateApiZiprApiPatchResolve(
  specPath: specPath,
  resolutions: resolutions,
);

class ApplySummary {
  final BigInt replaced;
  final BigInt deleted;

  /// Path to the pre-apply archive backup. `None` on dry-run.
  final String? backupPath;

  const ApplySummary({
    required this.replaced,
    required this.deleted,
    this.backupPath,
  });

  @override
  int get hashCode =>
      replaced.hashCode ^ deleted.hashCode ^ backupPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApplySummary &&
          runtimeType == other.runtimeType &&
          replaced == other.replaced &&
          deleted == other.deleted &&
          backupPath == other.backupPath;
}

class ArchiveEntry {
  final String expr;
  final BigInt size;
  final BigInt compressedSize;

  /// True if this entry is itself an archive (zip/jar/war/ear). Its
  /// children are loaded lazily via `list_archive_segment(expr)`.
  final bool isArchive;

  const ArchiveEntry({
    required this.expr,
    required this.size,
    required this.compressedSize,
    required this.isArchive,
  });

  @override
  int get hashCode =>
      expr.hashCode ^
      size.hashCode ^
      compressedSize.hashCode ^
      isArchive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchiveEntry &&
          runtimeType == other.runtimeType &&
          expr == other.expr &&
          size == other.size &&
          compressedSize == other.compressedSize &&
          isArchive == other.isArchive;
}

class DiffEntry {
  final String path;

  /// "added", "removed", or "modified"
  final String kind;
  final bool contentChanged;
  final List<String> metadataChanges;

  const DiffEntry({
    required this.path,
    required this.kind,
    required this.contentChanged,
    required this.metadataChanges,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      kind.hashCode ^
      contentChanged.hashCode ^
      metadataChanges.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiffEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          kind == other.kind &&
          contentChanged == other.contentChanged &&
          metadataChanges == other.metadataChanges;
}

class DraftSummary {
  final BigInt matched;
  final BigInt unresolved;

  /// The generated TOML spec content
  final String specToml;

  /// Structured unresolved entries for UI resolution
  final List<UnresolvedEntry> unresolvedEntries;

  const DraftSummary({
    required this.matched,
    required this.unresolved,
    required this.specToml,
    required this.unresolvedEntries,
  });

  @override
  int get hashCode =>
      matched.hashCode ^
      unresolved.hashCode ^
      specToml.hashCode ^
      unresolvedEntries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DraftSummary &&
          runtimeType == other.runtimeType &&
          matched == other.matched &&
          unresolved == other.unresolved &&
          specToml == other.specToml &&
          unresolvedEntries == other.unresolvedEntries;
}

class Resolution {
  final String source;

  /// "pick" or "ignore"
  final String action;

  /// The chosen target path; only used when action == "pick"
  final String chosenTarget;

  const Resolution({
    required this.source,
    required this.action,
    required this.chosenTarget,
  });

  @override
  int get hashCode => source.hashCode ^ action.hashCode ^ chosenTarget.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Resolution &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          action == other.action &&
          chosenTarget == other.chosenTarget;
}

class RustBuildInfo {
  final String ziprVersion;
  final String ziprGitRev;

  const RustBuildInfo({required this.ziprVersion, required this.ziprGitRev});

  @override
  int get hashCode => ziprVersion.hashCode ^ ziprGitRev.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustBuildInfo &&
          runtimeType == other.runtimeType &&
          ziprVersion == other.ziprVersion &&
          ziprGitRev == other.ziprGitRev;
}

class UnresolvedEntry {
  final String source;
  final String reason;
  final List<String> candidates;

  const UnresolvedEntry({
    required this.source,
    required this.reason,
    required this.candidates,
  });

  @override
  int get hashCode => source.hashCode ^ reason.hashCode ^ candidates.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UnresolvedEntry &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          reason == other.reason &&
          candidates == other.candidates;
}
