// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `default_config`

/// List all entries in an archive recursively (including nested archives).
Future<List<ArchiveEntry>> listArchive({required String path}) =>
    RustLib.instance.api.crateApiZiprApiListArchive(path: path);

/// Extract a single entry from an archive (supports nested paths with `!/`).
/// If `output_path` is provided, writes to that file; otherwise returns bytes.
Future<Uint8List> extractEntry({
  required String zipExpr,
  required String outputPath,
}) => RustLib.instance.api.crateApiZiprApiExtractEntry(
  zipExpr: zipExpr,
  outputPath: outputPath,
);

/// Delete an entry from an archive.
Future<void> deleteEntry({required String zipExpr}) =>
    RustLib.instance.api.crateApiZiprApiDeleteEntry(zipExpr: zipExpr);

/// Replace an entry in an archive with the contents of a source file.
Future<void> replaceEntry({
  required String zipExpr,
  required String sourcePath,
}) => RustLib.instance.api.crateApiZiprApiReplaceEntry(
  zipExpr: zipExpr,
  sourcePath: sourcePath,
);

/// Diff two archives recursively and return the list of differences.
Future<List<DiffEntry>> diffArchives({
  required String left,
  required String right,
}) =>
    RustLib.instance.api.crateApiZiprApiDiffArchives(left: left, right: right);

/// Generate a patch draft TOML spec from a source directory.
/// Returns the summary and the TOML content.
Future<DraftSummary> patchDraft({
  required String archive,
  required String fromDir,
  required String output,
}) => RustLib.instance.api.crateApiZiprApiPatchDraft(
  archive: archive,
  fromDir: fromDir,
  output: output,
);

/// Apply a patch spec to an archive.
/// Set `dry_run` to true to preview without modifying.
Future<ApplySummary> patchApply({
  required String archive,
  required String spec,
  required bool dryRun,
}) => RustLib.instance.api.crateApiZiprApiPatchApply(
  archive: archive,
  spec: spec,
  dryRun: dryRun,
);

class ApplySummary {
  final BigInt replaced;
  final BigInt deleted;

  const ApplySummary({required this.replaced, required this.deleted});

  @override
  int get hashCode => replaced.hashCode ^ deleted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApplySummary &&
          runtimeType == other.runtimeType &&
          replaced == other.replaced &&
          deleted == other.deleted;
}

class ArchiveEntry {
  final String expr;
  final BigInt size;
  final BigInt compressedSize;

  const ArchiveEntry({
    required this.expr,
    required this.size,
    required this.compressedSize,
  });

  @override
  int get hashCode => expr.hashCode ^ size.hashCode ^ compressedSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchiveEntry &&
          runtimeType == other.runtimeType &&
          expr == other.expr &&
          size == other.size &&
          compressedSize == other.compressedSize;
}

class DiffEntry {
  final String path;

  /// "added", "removed", or "modified"
  final String kind;
  final bool contentChanged;
  final List<String> metadataChanges;

  const DiffEntry({
    required this.path,
    required this.kind,
    required this.contentChanged,
    required this.metadataChanges,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      kind.hashCode ^
      contentChanged.hashCode ^
      metadataChanges.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiffEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          kind == other.kind &&
          contentChanged == other.contentChanged &&
          metadataChanges == other.metadataChanges;
}

class DraftSummary {
  final BigInt matched;
  final BigInt unresolved;

  /// The generated TOML spec content
  final String specToml;

  const DraftSummary({
    required this.matched,
    required this.unresolved,
    required this.specToml,
  });

  @override
  int get hashCode =>
      matched.hashCode ^ unresolved.hashCode ^ specToml.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DraftSummary &&
          runtimeType == other.runtimeType &&
          matched == other.matched &&
          unresolved == other.unresolved &&
          specToml == other.specToml;
}
