name: zipr_tool
description: "归档差异与补丁工具"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.0
  window_manager: ^0.4.0
  file_picker: ^10.3.10
  desktop_drop: ^0.5.0
  package_info_plus: ^8.1.0
  rust_lib_test_env_dashboard:
    path: rust_builder
  flutter_rust_bridge: 2.12.0
  shared_ui:
    path: ../../packages/shared_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.30.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Sarasa Gothic SC
      fonts:
        - asset: assets/fonts/SarasaGothicSC-Regular.ttf
        - asset: assets/fonts/SarasaGothicSC-Bold.ttf
          weight: 700
    - family: Sarasa Mono SC
      fonts:
        - asset: assets/fonts/SarasaMonoSC-Regular.ttf
        - asset: assets/fonts/SarasaMonoSC-Bold.ttf
          weight: 700
