// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/zipr_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 2100231553;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_test_env_dashboard',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiZiprApiDeleteEntry({required String zipExpr});

  Future<List<DiffEntry>> crateApiZiprApiDiffArchives({
    required String left,
    required String right,
  });

  Future<Uint8List> crateApiZiprApiExtractEntry({
    required String zipExpr,
    required String outputPath,
  });

  Future<List<ArchiveEntry>> crateApiZiprApiListArchive({required String path});

  Future<ApplySummary> crateApiZiprApiPatchApply({
    required String archive,
    required String spec,
    required bool dryRun,
  });

  Future<DraftSummary> crateApiZiprApiPatchDraft({
    required String archive,
    required String fromDir,
    required String output,
  });

  Future<void> crateApiZiprApiReplaceEntry({
    required String zipExpr,
    required String sourcePath,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiZiprApiDeleteEntry({required String zipExpr}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(zipExpr, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiZiprApiDeleteEntryConstMeta,
        argValues: [zipExpr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZiprApiDeleteEntryConstMeta =>
      const TaskConstMeta(debugName: "delete_entry", argNames: ["zipExpr"]);

  @override
  Future<List<DiffEntry>> crateApiZiprApiDiffArchives({
    required String left,
    required String right,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(left, serializer);
          sse_encode_String(right, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_diff_entry,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiZiprApiDiffArchivesConstMeta,
        argValues: [left, right],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZiprApiDiffArchivesConstMeta =>
      const TaskConstMeta(
        debugName: "diff_archives",
        argNames: ["left", "right"],
      );

  @override
  Future<Uint8List> crateApiZiprApiExtractEntry({
    required String zipExpr,
    required String outputPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(zipExpr, serializer);
          sse_encode_String(outputPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiZiprApiExtractEntryConstMeta,
        argValues: [zipExpr, outputPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZiprApiExtractEntryConstMeta =>
      const TaskConstMeta(
        debugName: "extract_entry",
        argNames: ["zipExpr", "outputPath"],
      );

  @override
  Future<List<ArchiveEntry>> crateApiZiprApiListArchive({
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_archive_entry,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiZiprApiListArchiveConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZiprApiListArchiveConstMeta =>
      const TaskConstMeta(debugName: "list_archive", argNames: ["path"]);

  @override
  Future<ApplySummary> crateApiZiprApiPatchApply({
    required String archive,
    required String spec,
    required bool dryRun,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(archive, serializer);
          sse_encode_String(spec, serializer);
          sse_encode_bool(dryRun, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_apply_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiZiprApiPatchApplyConstMeta,
        argValues: [archive, spec, dryRun],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZiprApiPatchApplyConstMeta => const TaskConstMeta(
    debugName: "patch_apply",
    argNames: ["archive", "spec", "dryRun"],
  );

  @override
  Future<DraftSummary> crateApiZiprApiPatchDraft({
    required String archive,
    required String fromDir,
    required String output,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(archive, serializer);
          sse_encode_String(fromDir, serializer);
          sse_encode_String(output, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_draft_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiZiprApiPatchDraftConstMeta,
        argValues: [archive, fromDir, output],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZiprApiPatchDraftConstMeta => const TaskConstMeta(
    debugName: "patch_draft",
    argNames: ["archive", "fromDir", "output"],
  );

  @override
  Future<void> crateApiZiprApiReplaceEntry({
    required String zipExpr,
    required String sourcePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(zipExpr, serializer);
          sse_encode_String(sourcePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiZiprApiReplaceEntryConstMeta,
        argValues: [zipExpr, sourcePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZiprApiReplaceEntryConstMeta =>
      const TaskConstMeta(
        debugName: "replace_entry",
        argNames: ["zipExpr", "sourcePath"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ApplySummary dco_decode_apply_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ApplySummary(
      replaced: dco_decode_usize(arr[0]),
      deleted: dco_decode_usize(arr[1]),
    );
  }

  @protected
  ArchiveEntry dco_decode_archive_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ArchiveEntry(
      expr: dco_decode_String(arr[0]),
      size: dco_decode_u_64(arr[1]),
      compressedSize: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DiffEntry dco_decode_diff_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DiffEntry(
      path: dco_decode_String(arr[0]),
      kind: dco_decode_String(arr[1]),
      contentChanged: dco_decode_bool(arr[2]),
      metadataChanges: dco_decode_list_String(arr[3]),
    );
  }

  @protected
  DraftSummary dco_decode_draft_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DraftSummary(
      matched: dco_decode_usize(arr[0]),
      unresolved: dco_decode_usize(arr[1]),
      specToml: dco_decode_String(arr[2]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ArchiveEntry> dco_decode_list_archive_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_archive_entry).toList();
  }

  @protected
  List<DiffEntry> dco_decode_list_diff_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_diff_entry).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ApplySummary sse_decode_apply_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_replaced = sse_decode_usize(deserializer);
    var var_deleted = sse_decode_usize(deserializer);
    return ApplySummary(replaced: var_replaced, deleted: var_deleted);
  }

  @protected
  ArchiveEntry sse_decode_archive_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_expr = sse_decode_String(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    var var_compressedSize = sse_decode_u_64(deserializer);
    return ArchiveEntry(
      expr: var_expr,
      size: var_size,
      compressedSize: var_compressedSize,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DiffEntry sse_decode_diff_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_contentChanged = sse_decode_bool(deserializer);
    var var_metadataChanges = sse_decode_list_String(deserializer);
    return DiffEntry(
      path: var_path,
      kind: var_kind,
      contentChanged: var_contentChanged,
      metadataChanges: var_metadataChanges,
    );
  }

  @protected
  DraftSummary sse_decode_draft_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_matched = sse_decode_usize(deserializer);
    var var_unresolved = sse_decode_usize(deserializer);
    var var_specToml = sse_decode_String(deserializer);
    return DraftSummary(
      matched: var_matched,
      unresolved: var_unresolved,
      specToml: var_specToml,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ArchiveEntry> sse_decode_list_archive_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ArchiveEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_archive_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<DiffEntry> sse_decode_list_diff_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DiffEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_diff_entry(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_apply_summary(ApplySummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.replaced, serializer);
    sse_encode_usize(self.deleted, serializer);
  }

  @protected
  void sse_encode_archive_entry(ArchiveEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.expr, serializer);
    sse_encode_u_64(self.size, serializer);
    sse_encode_u_64(self.compressedSize, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_diff_entry(DiffEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_bool(self.contentChanged, serializer);
    sse_encode_list_String(self.metadataChanges, serializer);
  }

  @protected
  void sse_encode_draft_summary(DraftSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.matched, serializer);
    sse_encode_usize(self.unresolved, serializer);
    sse_encode_String(self.specToml, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_archive_entry(
    List<ArchiveEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_archive_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_diff_entry(
    List<DiffEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_diff_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
